import React, { useState } from 'react';
import { Check, Zap, Cpu, ChevronUp, ChevronDown } from 'lucide-react';
import { AVAILABLE_TOOLS } from '../config/data';
import { CodeBlock } from '../components/UI';

const AutomationView = () => {
    const [step, setStep] = useState(1);
    const [selectedTools, setSelectedTools] = useState([]);
    const [automationMode, setAutomationMode] = useState('');
    const [toolDescriptions, setToolDescriptions] = useState({});

    const next = (s) => setStep(s);
    const reset = () => { setStep(1); setSelectedTools([]); setToolDescriptions({}); setAutomationMode(''); };
    const toggleTool = (t) => setSelectedTools(prev => prev.includes(t) ? prev.filter(x => x !== t) : [...prev, t]);
    const updateDescription = (t, v) => setToolDescriptions(prev => ({...prev, [t]: v}));
    const moveTool = (index, direction) => {
        const newTools = [...selectedTools];
        if (index + direction < 0 || index + direction >= newTools.length) return;
        const temp = newTools[index]; newTools[index] = newTools[index + direction]; newTools[index + direction] = temp;
        setSelectedTools(newTools);
    };
    const generateN8nJson = () => {
        const nodes = selectedTools.map((tool, index) => ({
          parameters: {}, name: tool, type: "n8n-nodes-base." + tool.toLowerCase().replace(' ', ''),
          typeVersion: 1, position: [250 + (index * 200), 300], notes: toolDescriptions[tool] || (index === 0 ? "Trigger" : "Action")
        }));
        nodes.unshift({ parameters: {}, name: "Start", type: "n8n-nodes-base.start", typeVersion: 1, position: [50, 300] });
        const connections = {};
        for (let i = 0; i < nodes.length - 1; i++) { connections[nodes[i].name] = { main: [[{ node: nodes[i+1].name, type: "main", index: 0 }]] }; }
        return JSON.stringify({ nodes, connections }, null, 2);
    };
    
    return (
    <div className="bg-slate-50 dark:bg-gray-800 border border-slate-200 dark:border-gray-700 rounded-xl p-8 text-center max-w-2xl mx-auto my-8 min-h-[400px] flex flex-col justify-center">
      {step === 1 && (<div className="animate-in fade-in slide-in-from-bottom-4 duration-500"><h3 className="text-2xl font-black text-blue-900 dark:text-blue-300 mb-6">1. Wie oft führst du den Prozess aus?</h3><div className="flex flex-wrap gap-4 justify-center"><button onClick={() => next(2)} className="px-6 py-3 bg-white dark:bg-gray-700 border-2 border-blue-600 dark:border-blue-500 text-blue-600 dark:text-blue-300 font-bold rounded-full hover:bg-blue-600 hover:text-white transition-all">Täglich / Wöchentlich</button><button onClick={() => next(2)} className="px-6 py-3 bg-white dark:bg-gray-700 border-2 border-blue-600 dark:border-blue-500 text-blue-600 dark:text-blue-300 font-bold rounded-full hover:bg-blue-600 hover:text-white transition-all">Monatlich (viele Daten)</button><button onClick={() => next(99)} className="px-6 py-3 bg-white dark:bg-gray-700 border-2 border-gray-300 dark:border-gray-600 text-gray-500 dark:text-gray-400 font-bold rounded-full hover:border-gray-400 transition-all">Selten (1-2x Jahr)</button></div></div>)}
      {step === 2 && (<div className="animate-in fade-in slide-in-from-bottom-4 duration-500"><h3 className="text-2xl font-black text-blue-900 dark:text-blue-300 mb-6">2. Folgt der Prozess festen Regeln?</h3><div className="bg-white dark:bg-gray-700 p-4 rounded-lg text-left mb-6 text-sm text-gray-600 dark:text-gray-300 border border-gray-200 dark:border-gray-600 inline-block"><strong>Beispiel für JA:</strong> "Wenn E-Mail Betreff 'Rechnung' enthält &rarr; speichere Anhang."</div><div className="flex flex-wrap gap-4 justify-center"><button onClick={() => next(3)} className="px-6 py-3 bg-white dark:bg-gray-700 border-2 border-blue-600 dark:border-blue-500 text-blue-600 dark:text-blue-300 font-bold rounded-full hover:bg-blue-600 hover:text-white transition-all">Ja, feste Logik</button><button onClick={() => next(98)} className="px-6 py-3 bg-white dark:bg-gray-700 border-2 border-gray-300 dark:border-gray-600 text-gray-500 dark:text-gray-400 font-bold rounded-full hover:border-gray-400 transition-all">Nein, Bauchgefühl nötig</button></div></div>)}
      {step === 3 && (<div className="animate-in fade-in slide-in-from-bottom-4 duration-500"><h3 className="text-2xl font-black text-blue-900 dark:text-blue-300 mb-2">3. Welche Tools sind beteiligt?</h3><div className="grid grid-cols-2 gap-3 text-left mb-6 max-w-md mx-auto">{AVAILABLE_TOOLS.map(tool => (<div key={tool} onClick={() => toggleTool(tool)} className={`p-3 border rounded-lg cursor-pointer flex items-center justify-between transition-all ${selectedTools.includes(tool) ? 'border-blue-600 bg-blue-50 dark:bg-blue-900/30 dark:border-blue-500' : 'border-gray-200 dark:border-gray-600 dark:bg-gray-700 hover:border-blue-300'}`}><span className="font-medium text-sm dark:text-gray-200">{tool}</span>{selectedTools.includes(tool) && <Check size={16} className="text-blue-600 dark:text-blue-400"/>}</div>))}</div><div className="flex justify-center"><button onClick={() => selectedTools.length > 0 ? next(4) : alert('Bitte wähle mindestens ein Tool.')} className="px-8 py-3 bg-blue-600 text-white font-bold rounded-full hover:bg-blue-700 transition-all shadow-lg shadow-blue-200">API Check & Weiter &rarr;</button></div></div>)}
      {step === 4 && (<div className="animate-in fade-in slide-in-from-bottom-4 duration-500"><h3 className="text-2xl font-black text-blue-900 dark:text-blue-300 mb-6">4. Wie komplex ist der Ablauf?</h3><div className="flex flex-col gap-4 max-w-sm mx-auto"><button onClick={() => { setAutomationMode('zapier'); next(5); }} className="p-4 bg-white dark:bg-gray-700 border-2 border-gray-200 dark:border-gray-600 rounded-xl hover:border-blue-600 hover:shadow-md transition-all text-left group"><div className="flex items-center gap-2 font-bold text-lg mb-1 dark:text-white group-hover:text-blue-600 dark:group-hover:text-blue-400"><Zap size={20}/> Einfach / Linear</div><div className="text-xs text-gray-500 dark:text-gray-400">"Wenn das passiert, dann mach das." (Z.B. Neuer Lead &rarr; E-Mail senden)</div></button><button onClick={() => { setAutomationMode('n8n'); next(5); }} className="p-4 bg-white dark:bg-gray-700 border-2 border-gray-200 dark:border-gray-600 rounded-xl hover:border-blue-600 hover:shadow-md transition-all text-left group"><div className="flex items-center gap-2 font-bold text-lg mb-1 dark:text-white group-hover:text-blue-600 dark:group-hover:text-blue-400"><Cpu size={20}/> Komplex / Logik</div><div className="text-xs text-gray-500 dark:text-gray-400">Mehrere Schritte, Bedingungen, Berechnungen oder DSGVO-kritische Daten.</div></button></div></div>)}
      {step === 5 && (<div className="animate-in fade-in slide-in-from-bottom-4 duration-500 text-left"><h3 className="text-2xl font-black text-blue-900 dark:text-blue-300 mb-2 text-center">5. Konfigurator ({automationMode})</h3><div className="space-y-4 mb-8">{selectedTools.map((tool, index) => (<div key={tool} className="bg-white dark:bg-gray-700 p-4 rounded-lg border border-gray-200 dark:border-gray-600 flex flex-col md:flex-row gap-4 items-center"><div className="flex items-center gap-3 w-full md:w-1/3"><div className="w-8 h-8 rounded-full bg-blue-100 dark:bg-blue-900 text-blue-600 dark:text-blue-300 flex items-center justify-center font-bold flex-shrink-0">{index + 1}</div><div className="flex flex-col"><span className="font-bold dark:text-white">{tool}</span><span className={`text-xs uppercase px-2 py-0.5 rounded w-max ${index === 0 ? 'bg-orange-100 dark:bg-orange-900/40 text-orange-700 dark:text-orange-300' : 'bg-gray-100 dark:bg-gray-600 text-gray-500 dark:text-gray-300'}`}>{index === 0 ? '⚡ Trigger' : '▶ Action'}</span></div><div className="flex flex-col ml-auto"><button onClick={() => moveTool(index, -1)} disabled={index === 0} className="text-gray-400 hover:text-blue-600 disabled:opacity-20 disabled:hover:text-gray-400"><ChevronUp size={16} /></button><button onClick={() => moveTool(index, 1)} disabled={index === selectedTools.length - 1} className="text-gray-400 hover:text-blue-600 disabled:opacity-20 disabled:hover:text-gray-400"><ChevronDown size={16} /></button></div></div><input type="text" placeholder={index === 0 ? "Z.B. Neuer Kontakt erstellt" : "Z.B. Nachricht in Channel senden"} className="flex-1 p-2 border border-gray-300 dark:border-gray-500 dark:bg-gray-800 dark:text-white rounded text-sm w-full" value={toolDescriptions[tool] || ''} onChange={(e) => updateDescription(tool, e.target.value)} /></div>))}</div><div className="flex justify-center"><button onClick={() => next(6)} className="px-8 py-3 bg-blue-600 text-white font-bold rounded-full hover:bg-blue-700 transition-all shadow-lg shadow-blue-200 flex items-center gap-2">{automationMode === 'n8n' ? <Cpu size={18}/> : <Zap size={18}/>} Blueprint generieren</button></div></div>)}
      {step === 6 && (<div className="animate-in fade-in slide-in-from-bottom-4 duration-500"><div className="mb-6"><div className="w-16 h-16 bg-green-100 dark:bg-green-900/30 text-green-600 dark:text-green-400 rounded-full flex items-center justify-center mx-auto mb-4"><Check size={32}/></div><h3 className="text-2xl font-black text-gray-900 dark:text-white">Dein {automationMode === 'n8n' ? 'Workflow Blueprint' : 'Rezept'} ist fertig!</h3></div>{automationMode === 'n8n' ? (<div className="text-left"><p className="text-sm text-gray-600 dark:text-gray-400 mb-2 text-center">Kopiere diesen JSON-Code und füge ihn direkt in n8n (Strg+V) ein.</p><CodeBlock code={generateN8nJson()} label="n8n Workflow JSON" /></div>) : (<div className="bg-white dark:bg-gray-800 p-6 rounded-xl border border-gray-200 dark:border-gray-700 text-left mb-6"><h4 className="font-bold text-lg mb-4 border-b dark:border-gray-700 pb-2 flex items-center gap-2 text-gray-900 dark:text-white"><Zap className="text-orange-500"/> Zapier Rezept</h4><ol className="space-y-4 relative border-l-2 border-gray-100 dark:border-gray-700 ml-3 pl-6">{selectedTools.map((tool, i) => (<li key={i} className="relative"><span className="absolute -left-[31px] top-0 w-6 h-6 bg-blue-600 text-white rounded-full flex items-center justify-center text-xs font-bold">{i+1}</span><div className="font-bold text-gray-900 dark:text-white">{tool}</div><div className="text-sm text-gray-600 dark:text-gray-400">{toolDescriptions[tool] || (i===0 ? "Trigger Event wählen" : "Action definieren")}</div></li>))}</ol></div>)}<button onClick={reset} className="mt-4 text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 text-sm underline">Neuen Check starten</button></div>)}
      {(step === 99 || step === 98) && (<div className="text-center"><div className="text-4xl mb-4">{step===99?'❌':'🧠'}</div><h3 className="font-bold text-xl mb-2 text-gray-900 dark:text-white">{step===99?'Nicht automatisieren':'Manuelle Bearbeitung empfohlen'}</h3><p className="text-gray-600 dark:text-gray-400 mb-6">{step===99?'Der Aufwand lohnt sich nicht für so seltene Fälle.':'Prozesse, die "Bauchgefühl" brauchen, sind schwer zu automatisieren.'}</p><button onClick={reset} className="underline text-gray-500 hover:text-blue-600">Neu starten</button></div>)}
    </div>
  );
};

export default AutomationView;