import React from 'react';
import { Flag } from 'lucide-react';
import { InfoBox } from '../components/UI';
import { TICKET_PHASES, SNIPPETS } from '../config/data';

export default function SupportView({ openFeedback }) {
    return (
    <div className="max-w-4xl mx-auto animate-in slide-in-from-bottom-4 duration-500">
        <div className="flex justify-between items-start mb-6">
            <div><h2 className="text-3xl font-black text-gray-900 dark:text-white mb-2">Customer Support Playbook</h2><div className="bg-blue-50 dark:bg-blue-900/20 text-blue-800 dark:text-blue-200 px-4 py-2 rounded-lg inline-block text-sm font-medium">Ziel: Wir lösen Probleme schnell, freundlich und im "K5 Tone of Voice".</div></div>
            <button onClick={() => openFeedback('Support Playbook')} className="text-gray-400 hover:text-red-500"><Flag size={20}/></button>
        </div>
        <div className="grid md:grid-cols-2 gap-8 mb-12">
            <InfoBox title="Wichtige Regeln" type="warning"><ul className="list-disc pl-5 space-y-1"><li><strong>24h Regel:</strong> Jede Mail wird innerhalb von 24h beantwortet.</li><li><strong>Du-Kultur:</strong> Wir duzen unsere Kunden konsequent.</li><li><strong>CC Clean-Up:</strong> "K5 GmbH" aus Empfängerzeile entfernen.</li><li><strong>Schreibweise:</strong> K5 FUTURE RETAIL CONFERENCE 2026</li><li><strong>Kulanz:</strong> Code <code>welovek5</code> (10%) bei Ärger (nur vor Kauf!).</li></ul></InfoBox>
            <InfoBox title="Slack Channels" type="info"><div className="space-y-2"><div className="flex justify-between"><code className="bg-white dark:bg-gray-700 dark:text-gray-200 px-2 py-1 rounded border dark:border-gray-600">@customersupport</code><span>Team</span></div><div className="flex justify-between"><code className="bg-white dark:bg-gray-700 dark:text-gray-200 px-2 py-1 rounded border dark:border-gray-600">@mgmt</code><span>Notfälle</span></div></div></InfoBox>
        </div>
        <div className="grid md:grid-cols-2 gap-8 mb-12">
            <div><h3 className="text-xl font-bold mb-4 text-gray-900 dark:text-white">Ticket Preise</h3><div className="bg-white dark:bg-gray-800 rounded-xl shadow-sm border border-gray-200 dark:border-gray-700 overflow-hidden"><table className="w-full text-sm"><thead className="bg-gray-50 dark:bg-gray-700 font-bold border-b border-gray-200 dark:border-gray-600"><tr><th className="px-4 py-2 text-left">Phase</th><th className="px-4 py-2 text-right">Retailer</th><th className="px-4 py-2 text-right text-gray-400">Non-Ret.</th></tr></thead><tbody className="divide-y divide-gray-100 dark:divide-gray-700">{TICKET_PHASES.map((p, i) => (<tr key={i}><td className="px-4 py-2 font-medium">{p.name}</td><td className="px-4 py-2 font-bold text-blue-600 text-right">{p.price}</td><td className="px-4 py-2 text-gray-400 text-right">{p.nonRetailer}</td></tr>))}</tbody></table></div></div>
            <div><h3 className="text-xl font-bold mb-4 text-gray-900 dark:text-white">Retailer Definition</h3><div className="bg-amber-50 dark:bg-amber-900/20 p-4 rounded-xl border border-amber-200 dark:border-amber-800 text-sm text-amber-900 dark:text-amber-200"><p className="mb-2 font-bold">Unterscheidung ist kritisch für Pricing!</p><ul className="list-disc pl-4 space-y-1"><li><strong>Retailer:</strong> Shops (Online/Stationär), Bildung, Verlage, Hersteller.</li><li><strong>Non-Retailer:</strong> Agenturen, Berater, Dienstleister (Teurer!).</li></ul></div></div>
        </div>
        <h3 className="text-xl font-bold mb-6 text-gray-900 dark:text-white border-b dark:border-gray-700 pb-2">Eskalations-Matrix (L1 - L3)</h3>
        <div className="bg-white dark:bg-gray-800 rounded-xl shadow-sm border border-gray-200 dark:border-gray-700 overflow-hidden mb-12"><table className="w-full text-sm text-left"><thead className="bg-gray-50 dark:bg-gray-700 text-gray-500 dark:text-gray-300 uppercase font-bold"><tr><th className="px-6 py-4">Level</th><th className="px-6 py-4">Zuständigkeit</th><th className="px-6 py-4">Beispiel</th></tr></thead><tbody className="divide-y divide-gray-100 dark:divide-gray-700"><tr className="hover:bg-blue-50/50 dark:hover:bg-gray-700/50"><td className="px-6 py-4 font-bold text-blue-600 dark:text-blue-400">L1 Support <br/><span className="text-xs font-normal text-gray-500 dark:text-gray-400">Happiness Team</span></td><td className="px-6 py-4 dark:text-gray-300">Standard Anfragen, Infos, Umschreibung</td><td className="px-6 py-4 text-gray-500 dark:text-gray-400">"Wo ist mein Ticket?"</td></tr><tr className="hover:bg-blue-50/50 dark:hover:bg-gray-700/50"><td className="px-6 py-4 font-bold text-purple-600 dark:text-purple-400">L2 Support <br/><span className="text-xs font-normal text-gray-500 dark:text-gray-400">Leads</span></td><td className="px-6 py-4 dark:text-gray-300">Kleine Kulanz, Eskalation, Storno (Einzelfall)</td><td className="px-6 py-4 text-gray-500 dark:text-gray-400">Kunde beschwert sich.</td></tr><tr className="hover:bg-blue-50/50 dark:hover:bg-gray-700/50"><td className="px-6 py-4 font-bold text-red-600 dark:text-red-400">L3 Support <br/><span className="text-xs font-normal text-gray-500 dark:text-gray-400">Owner</span></td><td className="px-6 py-4 dark:text-gray-300">Kulanz &gt; 10%, Große Stornos, Legal</td><td className="px-6 py-4 text-gray-500 dark:text-gray-400">Gruppen-Storno, Anwalt.</td></tr></tbody></table></div>
        <h3 className="text-xl font-bold mb-6 text-gray-900 dark:text-white border-b dark:border-gray-700 pb-2">Textbausteine (Snippets)</h3>
        <div className="grid gap-4">{SNIPPETS.map((snip, i) => (<div key={i} className="border border-gray-200 dark:border-gray-700 rounded-lg bg-white dark:bg-gray-800 overflow-hidden group"><div className="bg-gray-50 dark:bg-gray-700 px-4 py-3 font-bold text-sm flex justify-between items-center cursor-pointer group-hover:bg-gray-100 dark:group-hover:bg-gray-600 text-gray-900 dark:text-white"><span className="flex items-center gap-2">{snip.title} <Flag size={14} className="text-gray-300 hover:text-red-500" onClick={(e) => {e.stopPropagation(); openFeedback(`Snippet: ${snip.title}`)}}/></span><span className="text-xs bg-white dark:bg-gray-800 px-2 py-1 rounded border dark:border-gray-600">Copy</span></div><div className="p-4 text-xs font-mono bg-white dark:bg-gray-800 text-gray-600 dark:text-gray-300 whitespace-pre-wrap leading-relaxed border-t border-gray-100 dark:border-gray-700">{snip.text}</div></div>))}</div>
    </div>
    );
}