import React from 'react';
import { Flag, FileText, Check, AlertTriangle } from 'lucide-react';
import { InfoBox, ChecklistItem } from '../components/UI';

export default function VivenuView({ openFeedback }) {
    return (
    <div className="max-w-4xl mx-auto animate-in slide-in-from-bottom-4 duration-500">
        <div className="flex justify-between items-start mb-6"><div><h2 className="text-3xl font-black text-gray-900 dark:text-white">Vivenu Event Setup</h2></div><button onClick={() => openFeedback('Vivenu Setup')} className="text-gray-400 hover:text-red-500"><Flag size={20}/></button></div>
        <InfoBox type="warning" title="WICHTIG">Immer auf <strong>SPEICHERN</strong> klicken. Nur aufgeführte Punkte ändern.</InfoBox>
        <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-100 dark:border-blue-800 rounded-xl p-6 mb-8"><h3 className="font-bold text-blue-900 dark:text-blue-300 mb-3 flex items-center gap-2"><FileText size={20}/> 📂 Benötigte Assets</h3><ul className="grid grid-cols-2 gap-2 text-sm text-blue-800 dark:text-blue-200"><li className="flex items-center gap-2"><Check size={14}/> Titelbild</li><li className="flex items-center gap-2"><Check size={14}/> Design für Tickets (PDF, Wallet)</li><li className="flex items-center gap-2"><Check size={14}/> Ticketfooter</li><li className="flex items-center gap-2"><Check size={14}/> Start/Endzeit & Eventname</li></ul></div>
        <div className="space-y-6">
             <div className="bg-white dark:bg-gray-800 p-6 rounded-xl border border-gray-200 dark:border-gray-700"><h3 className="font-bold text-lg mb-4 text-gray-900 dark:text-white">1. Neues Event & Grundeinstellungen</h3><table className="w-full text-sm"><tbody className="divide-y divide-gray-100 dark:divide-gray-700"><tr><td className="py-3 font-bold text-gray-700 dark:text-gray-300">Event Typ</td><td className="py-3 dark:text-gray-200">Einfaches Event</td></tr><tr><td className="py-3 font-bold text-gray-700 dark:text-gray-300">Tickets pro Kauf</td><td className="py-3 dark:text-gray-200">Klein: 3-5 | Konferenz: 20</td></tr><tr><td className="py-3 font-bold text-gray-700 dark:text-gray-300">SEO Index</td><td className="py-3"><span className="bg-red-100 dark:bg-red-900/30 text-red-800 dark:text-red-300 px-2 py-1 rounded text-xs font-bold">NO INDEX</span></td></tr></tbody></table></div>
             <div className="bg-white dark:bg-gray-800 p-6 rounded-xl border border-gray-200 dark:border-gray-700"><h3 className="font-bold text-lg mb-4 text-gray-900 dark:text-white">2. & 3. Darstellung</h3><ul className="text-sm space-y-3 text-gray-600 dark:text-gray-300"><li className="flex items-center gap-3"><Check size={14} className="text-green-500"/> Titelbild & Farbe hinterlegen</li><li className="flex items-center gap-3"><Check size={14} className="text-green-500"/> "Invite Only" / Startpreis auf "Verstecken" setzen</li></ul></div>
             <div className="bg-white dark:bg-gray-800 p-6 rounded-xl border border-gray-200 dark:border-gray-700"><h3 className="font-bold text-lg mb-4 text-gray-900 dark:text-white">4. Ticketkategorien</h3><InfoBox type="info"><strong>WICHTIG:</strong> "Kategorien" in Vivenu sind NICHT unsere Ticketkategorien. Unsere Kategorien heißen in Vivenu <strong>Tickettypen</strong>.</InfoBox><p className="text-sm text-gray-600 dark:text-gray-300 mt-2">Alle Kategorien und Abfragen müssen strikt nach den <span className="text-blue-600 dark:text-blue-400 font-bold cursor-pointer">Ticket-Guidelines</span> erstellt werden.</p></div>
             <div className="bg-white dark:bg-gray-800 p-6 rounded-xl border border-gray-200 dark:border-gray-700"><h3 className="font-bold text-lg mb-4 text-gray-900 dark:text-white">5. Verkauf</h3><table className="w-full text-sm"><tbody className="divide-y divide-gray-100 dark:divide-gray-700"><tr><td className="py-3 font-bold text-gray-700 dark:text-gray-300">Steuern</td><td className="py-3 font-bold text-blue-600 dark:text-blue-400">19% (Pflicht!)</td></tr><tr><td className="py-3 font-bold text-gray-700 dark:text-gray-300">Start</td><td className="py-3 dark:text-gray-200">"Ab sofort"</td></tr><tr><td className="py-3 font-bold text-gray-700 dark:text-gray-300">Rabatte</td><td className="py-3 dark:text-gray-200">Nur nach Absprache</td></tr></tbody></table></div>
             <div className="grid md:grid-cols-2 gap-6"><div className="bg-white dark:bg-gray-800 p-6 rounded-xl border border-gray-200 dark:border-gray-700"><h4 className="font-bold text-sm uppercase text-gray-400 mb-3">6. Daten & Personalisierung</h4><p className="text-sm text-gray-600 dark:text-gray-300"><strong>Personalisierung</strong> ist erforderlich.</p></div><div className="bg-white dark:bg-gray-800 p-6 rounded-xl border border-gray-200 dark:border-gray-700"><h4 className="font-bold text-sm uppercase text-gray-400 mb-3">7. Geheime Shops</h4><p className="text-sm text-gray-600 dark:text-gray-300">Nur nach Absprache erstellen.</p></div><div className="bg-white dark:bg-gray-800 p-6 rounded-xl border border-gray-200 dark:border-gray-700"><h4 className="font-bold text-sm uppercase text-gray-400 mb-3">8. Ticket Design</h4><p className="text-sm text-gray-600 dark:text-gray-300">Grafiken einfügen und Schriftfarbe anpassen (Lesbarkeit!).</p></div><div className="bg-red-50 dark:bg-red-900/20 p-6 rounded-xl border border-red-200 dark:border-red-800"><h4 className="font-bold text-sm uppercase text-red-800 dark:text-red-300 mb-3 flex items-center gap-2"><AlertTriangle size={16}/> 9. Gebühren</h4><p className="text-sm text-red-700 dark:text-red-400 font-bold">NICHTS ANFASSEN!</p></div><div className="bg-white dark:bg-gray-800 p-6 rounded-xl border border-gray-200 dark:border-gray-700"><h4 className="font-bold text-sm uppercase text-gray-400 mb-3">10. Tracking</h4><p className="text-sm text-gray-600 dark:text-gray-300">Tags entsprechend Tagging-Konzept einfügen.</p></div><div className="bg-white dark:bg-gray-800 p-6 rounded-xl border border-gray-200 dark:border-gray-700"><h4 className="font-bold text-sm uppercase text-gray-400 mb-3">12. Emails</h4><p className="text-sm text-gray-600 dark:text-gray-300">Alle Mails müssen mit dem <strong>Marketing Team</strong> abgesprochen werden.</p></div></div>
             <h3 className="font-bold text-xl mt-12 mb-4 text-gray-900 dark:text-white">Ready-to-Go Check</h3><div className="bg-white dark:bg-gray-800 p-6 rounded-xl border border-gray-200 dark:border-gray-700 shadow-sm"><ChecklistItem label="Gefilterte Übersicht des Ticketkaufs erstellen" /><ChecklistItem label="Link in Slack Canvas posten" /><ChecklistItem label="Shop einer weiteren Person zum Double Check geben" /><ChecklistItem label="Test Ticket gekauft" /><ChecklistItem label="Automatisierungen angelegt / gebrieft" /><ChecklistItem label="Shop auf der LP integriert" /></div>
        </div>
    </div>
    );
}