import React from 'react';
import { Flag, ArrowRight, FileText, Cpu, Send, Database, BarChart } from 'lucide-react';
import { InfoBox, ChecklistItem, CodeBlock } from '../components/UI';
import { VOTING_BLUEPRINT } from '../config/data';

export default function VotingView({ openFeedback }) {
    return (
    <div className="max-w-4xl mx-auto animate-in slide-in-from-bottom-4 duration-500">
        <div className="flex justify-between items-start mb-6">
            <h2 className="text-3xl font-black text-gray-900 dark:text-white mb-6">Voting Guidelines & Setup</h2>
            <button onClick={() => openFeedback('Voting System')} className="text-gray-400 hover:text-red-500"><Flag size={20}/></button>
        </div>
        <InfoBox title="Zielsetzung" type="info">Fairer Wettbewerb durch intelligente Verifizierung (Double-Opt-In). <strong>Ein User = Eine Stimme</strong> pro Kategorie.</InfoBox>
        <h3 className="text-xl font-bold mb-6 mt-12 text-gray-900 dark:text-white">01 // Der User Flow</h3>
        <div className="bg-white dark:bg-gray-800 p-6 rounded-xl border border-gray-200 dark:border-gray-700 shadow-sm mb-12"><div className="flex flex-col md:flex-row gap-4 items-stretch text-center"><div className="flex-1 p-4 bg-gray-50 dark:bg-gray-700 rounded-lg border border-gray-100 dark:border-gray-600"><div className="font-bold text-lg mb-1 dark:text-white">1. Vote</div><div className="text-sm text-gray-500 dark:text-gray-400">User wählt Favorit & gibt Email ein.</div></div><div className="flex items-center justify-center text-gray-300 dark:text-gray-600"><ArrowRight/></div><div className="flex-1 p-4 bg-gray-50 dark:bg-gray-700 rounded-lg border border-gray-100 dark:border-gray-600"><div className="font-bold text-lg mb-1 dark:text-white">2. Check</div><div className="text-sm text-gray-500 dark:text-gray-400">Backend prüft Status (Neu/Bekannt).</div></div><div className="flex items-center justify-center text-gray-300 dark:text-gray-600"><ArrowRight/></div><div className="flex-1 p-4 bg-blue-50 dark:bg-blue-900/20 rounded-lg border border-blue-100 dark:border-blue-800 text-blue-800 dark:text-blue-200"><div className="font-bold text-lg mb-1">3. Verify</div><div className="text-sm">Bei neuen Usern: DOI-Mail senden.</div></div></div></div>
        <h3 className="text-xl font-bold mb-6 text-gray-900 dark:text-white">02 // Tech Stack</h3>
        <div className="grid grid-cols-2 md:grid-cols-5 gap-4 mb-8"><div className="bg-white dark:bg-gray-800 p-4 rounded-xl border border-gray-200 dark:border-gray-700 text-center"><FileText className="mx-auto mb-2 text-gray-400" size={24}/><div className="font-bold text-sm dark:text-white">Typeform</div><div className="text-xs text-gray-500 dark:text-gray-400">Frontend</div></div><div className="bg-white dark:bg-gray-800 p-4 rounded-xl border border-gray-200 dark:border-gray-700 text-center"><Cpu className="mx-auto mb-2 text-blue-600" size={24}/><div className="font-bold text-sm dark:text-white">n8n</div><div className="text-xs text-gray-500 dark:text-gray-400">Logic</div></div><div className="bg-white dark:bg-gray-800 p-4 rounded-xl border border-gray-200 dark:border-gray-700 text-center"><Send className="mx-auto mb-2 text-green-600" size={24}/><div className="font-bold text-sm dark:text-white">Brevo</div><div className="text-xs text-gray-500 dark:text-gray-400">Mail</div></div><div className="bg-white dark:bg-gray-800 p-4 rounded-xl border border-gray-200 dark:border-gray-700 text-center"><Database className="mx-auto mb-2 text-green-700" size={24}/><div className="font-bold text-sm dark:text-white">Sheets</div><div className="text-xs text-gray-500 dark:text-gray-400">DB</div></div><div className="bg-white dark:bg-gray-800 p-4 rounded-xl border border-gray-200 dark:border-gray-700 text-center"><BarChart className="mx-auto mb-2 text-yellow-600" size={24}/><div className="font-bold text-sm dark:text-white">Looker</div><div className="text-xs text-gray-500 dark:text-gray-400">Report</div></div></div>
        <h3 className="text-xl font-bold mb-4 mt-12 text-gray-900 dark:text-white">03 // Setup Requirements</h3><div className="bg-white dark:bg-gray-800 p-6 rounded-xl border border-gray-200 dark:border-gray-700 shadow-sm mb-12"><ul className="space-y-4"><li className="flex items-start gap-3"><FileText size={16}/><div className="flex-1"><strong className="block text-gray-900 dark:text-white">Typeform</strong><span className="text-sm text-gray-600 dark:text-gray-400">Erstelle <strong>ein Formular pro Kategorie</strong> (nicht alles in einem), um die Daten sauber zu trennen.</span></div></li><li className="flex items-start gap-3"><Database size={16}/><div className="flex-1"><strong className="block text-gray-900 dark:text-white">Google Sheets</strong><span className="text-sm text-gray-600 dark:text-gray-400">Nutze <strong>ein Master-Sheet</strong> für alle eingehenden Votes, um Duplikate kategorieübergreifend zu prüfen.</span></div></li><li className="flex items-start gap-3"><Send size={16}/><div className="flex-1"><strong className="block text-gray-900 dark:text-white">Brevo Templates</strong><span className="text-sm text-gray-600 dark:text-gray-400 block mb-1">Erstelle folgende 3 E-Mail-Vorlagen:</span><ul className="text-sm list-disc pl-4 space-y-1 text-gray-500 dark:text-gray-400"><li><strong>Verifizierung (DOI):</strong> "Bitte bestätige deine Stimme."</li><li><strong>Bestätigung:</strong> "Danke, deine Stimme wurde gezählt."</li><li><strong>Ablehnung:</strong> "Sorry, deine Stimme zählt nicht, da du in dieser Kategorie bereits abgestimmt hast."</li></ul></div></li></ul></div>
        <h3 className="text-xl font-bold mb-4 text-gray-900 dark:text-white">04 // n8n Blueprint Template</h3><p className="text-sm text-gray-600 dark:text-gray-400 mb-2">Kopiere diesen Code und füge ihn in n8n (Strg+V) ein, um den Workflow zu importieren.</p><CodeBlock code={VOTING_BLUEPRINT} /><h3 className="text-xl font-bold mb-4 mt-12 text-gray-900 dark:text-white">05 // Setup Checkliste</h3><div className="bg-white dark:bg-gray-800 p-6 rounded-xl border border-gray-200 dark:border-gray-700 shadow-sm mb-12"><ChecklistItem label="Typeforms erstellt & Webhook an n8n gesetzt?" /><ChecklistItem label="Brevo Templates (DOI, Bestätigung, Ablehnung) aktiv?" /><ChecklistItem label="n8n Workflow auf 'Active' geschaltet?" /><ChecklistItem label="Google Sheet mit Looker Studio verbunden?" /></div>
    </div>
    );
}