import React from 'react';
import { Flag, Layout, PenTool, Image, Globe } from 'lucide-react';
import { ChecklistItem } from '../components/UI';

export default function WebView({ openFeedback }) {
    return (
   <div className="max-w-4xl mx-auto animate-in slide-in-from-bottom-4 duration-500">
      <div className="flex justify-between items-start mb-6"><div><h2 className="text-3xl font-black text-gray-900 dark:text-white">Webseite Guidelines</h2><div className="bg-blue-50 dark:bg-blue-900/20 text-blue-800 dark:text-blue-200 px-4 py-2 rounded-lg inline-block text-sm font-medium">Ziel: Performance, Einheitlichkeit, Stabilität.</div></div><button onClick={() => openFeedback('Web Guidelines')} className="text-gray-400 hover:text-red-500"><Flag size={20}/></button></div>
      <div className="space-y-8">
         <div className="bg-white dark:bg-gray-800 p-6 rounded-xl border border-gray-200 dark:border-gray-700"><h3 className="font-bold text-lg mb-4 flex items-center gap-2 text-gray-900 dark:text-white"><Layout size={20} className="text-blue-600 dark:text-blue-400"/> 01 // Design & Layout</h3><div className="grid md:grid-cols-2 gap-4"><div className="bg-green-50 dark:bg-green-900/20 p-3 rounded border border-green-200 dark:border-green-800"><strong className="text-green-800 dark:text-green-400 block mb-1">DO</strong><div className="text-sm dark:text-gray-300">Nutze vordefinierte Blöcke</div><div className="text-sm dark:text-gray-300">Button-Stil "Primary" verwenden</div></div><div className="bg-red-50 dark:bg-red-900/20 p-3 rounded border border-red-200 dark:border-red-800"><strong className="text-red-800 dark:text-red-400 block mb-1">DON'T</strong><div className="text-sm dark:text-gray-300">Eigene Spalten bauen</div><div className="text-sm dark:text-gray-300">Farbe manuell ändern</div></div></div></div>
         <div className="bg-white dark:bg-gray-800 p-6 rounded-xl border border-gray-200 dark:border-gray-700"><h3 className="font-bold text-lg mb-4 flex items-center gap-2 text-gray-900 dark:text-white"><PenTool size={20} className="text-blue-600 dark:text-blue-400"/> 02 // Text & Inhalte</h3><div className="grid md:grid-cols-2 gap-4"><div className="bg-green-50 dark:bg-green-900/20 p-3 rounded border border-green-200 dark:border-green-800"><strong className="text-green-800 dark:text-green-400 block mb-1">DO</strong><div className="text-sm dark:text-gray-300">Anrede: <strong>Du/Euch</strong> GROSS</div><div className="text-sm dark:text-gray-300">Struktur: H1 &rarr; H2 &rarr; H3</div></div><div className="bg-red-50 dark:bg-red-900/20 p-3 rounded border border-red-200 dark:border-red-800"><strong className="text-red-800 dark:text-red-400 block mb-1">DON'T</strong><div className="text-sm dark:text-gray-300">Anrede: du/euch klein</div><div className="text-sm dark:text-gray-300">Überspringen: H1 &rarr; H4</div></div></div></div>
         <div className="bg-white dark:bg-gray-800 p-6 rounded-xl border border-gray-200 dark:border-gray-700"><h3 className="font-bold text-lg mb-4 flex items-center gap-2 text-gray-900 dark:text-white"><Image size={20} className="text-blue-600 dark:text-blue-400"/> 03 // Bilder & Medien</h3><div className="grid md:grid-cols-2 gap-4"><div className="bg-green-50 dark:bg-green-900/20 p-3 rounded border border-green-200 dark:border-green-800"><strong className="text-green-800 dark:text-green-400 block mb-1">DO</strong><div className="text-sm dark:text-gray-300">Format: <strong>WebP</strong> (immer!)</div><div className="text-sm dark:text-gray-300">Name: <code>team-2026.webp</code></div><div className="text-sm dark:text-gray-300">Update: Bild im CMS <strong>ersetzen</strong></div></div><div className="bg-red-50 dark:bg-red-900/20 p-3 rounded border border-red-200 dark:border-red-800"><strong className="text-red-800 dark:text-red-400 block mb-1">DON'T</strong><div className="text-sm dark:text-gray-300">JPG/PNG (wenn vermeidbar)</div><div className="text-sm dark:text-gray-300"><code>IMG_5920.jpg</code></div><div className="text-sm dark:text-gray-300">Neu hochladen</div></div></div></div>
         <div className="bg-white dark:bg-gray-800 p-6 rounded-xl border border-gray-200 dark:border-gray-700"><h3 className="font-bold text-lg mb-4 flex items-center gap-2 text-gray-900 dark:text-white"><Globe className="text-blue-600 dark:text-blue-400"/> 04 // SEO & URLs</h3><div className="grid md:grid-cols-2 gap-4"><div className="bg-green-50 dark:bg-green-900/20 p-3 rounded border border-green-200 dark:border-green-800"><strong className="text-green-800 dark:text-green-400 block mb-1">DO</strong><div className="text-sm dark:text-gray-300"><code>k5.de/podcast</code></div></div><div className="bg-red-50 dark:bg-red-900/20 p-3 rounded border border-red-200 dark:border-red-800"><strong className="text-red-800 dark:text-red-400 block mb-1">DON'T</strong><div className="text-sm dark:text-gray-300"><code>k5.de/k5-podcast</code> (Redundanz)</div></div></div></div>
         <div className="bg-white dark:bg-gray-800 p-6 rounded-xl border border-gray-200 dark:border-gray-700"><h3 className="font-bold text-lg mb-4 flex items-center gap-2 text-gray-900 dark:text-white"><Flag className="text-blue-600 dark:text-blue-400"/> 05 // Workflow</h3><div className="grid md:grid-cols-2 gap-4"><div className="bg-green-50 dark:bg-green-900/20 p-3 rounded border border-green-200 dark:border-green-800"><strong className="text-green-800 dark:text-green-400 block mb-1">DO</strong><div className="text-sm dark:text-gray-300">Live erst bei 100% fertig</div></div><div className="bg-red-50 dark:bg-red-900/20 p-3 rounded border border-red-200 dark:border-red-800"><strong className="text-red-800 dark:text-red-400 block mb-1">DON'T</strong><div className="text-sm dark:text-gray-300">Platzhaltertexte live stellen</div></div></div></div>
         <div className="bg-white dark:bg-gray-800 p-6 rounded-xl border border-gray-200 dark:border-gray-700 shadow-sm"><h3 className="font-bold text-xl mt-4 mb-4 text-gray-900 dark:text-white">Go-Live Checkliste</h3><ChecklistItem label="Seite 100% fertig?" /><ChecklistItem label="Anrede geprüft?" /><ChecklistItem label="Bilder optimiert?" /></div>
      </div>
   </div>
    );
}